before_script:
    - pacman -Syy --noconfirm; pacman -Syu --noconfirm; pacman-db-upgrade; rm -rf /var/cache/pacman/pkg/*.tar.xz

build:
    script:
        - cd src/
        - mkdir -p build; cd build
        - qmake -r ../Kinesix.pro; make distclean
        - make
        - cd ..
        - rm -rf output; mkdir output
        - cp build/Kinesix output/
